/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/query/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a query session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSessionRequest"];
                };
            };
            responses: {
                /** @description Session created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query/sessions/{sessionId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate SQL and execute a query session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RunSessionRequest"];
                };
            };
            responses: {
                /** @description Query executed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query/sessions/{sessionId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit feedback for a query session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackRequest"];
                };
            };
            responses: {
                /** @description Feedback stored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered data sources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data source list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataSourceListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Register a data source */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDataSourceRequest"];
                };
            };
            responses: {
                /** @description Data source created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataSourceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data-sources/{dataSourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a data source and its dependent data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dataSourceId: components["parameters"]["DataSourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data source deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data-sources/{dataSourceId}/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Introspect schema metadata for a data source */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dataSourceId: components["parameters"]["DataSourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Introspection job started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAcceptedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schema-objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List schema objects for a data source */
        get: {
            parameters: {
                query: {
                    data_source_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Schema objects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["SchemaObject"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/semantic-entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update semantic entity */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SemanticEntityRequest"];
                };
            };
            responses: {
                /** @description Semantic entity upserted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SemanticEntityResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metric-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update metric definition */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MetricDefinitionRequest"];
                };
            };
            responses: {
                /** @description Metric definition upserted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricDefinitionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/join-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update join policy */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JoinPolicyRequest"];
                };
            };
            responses: {
                /** @description Join policy upserted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinPolicyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rag/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger reindex for RAG documents */
        post: {
            parameters: {
                query: {
                    data_source_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reindex job started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAcceptedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all configured LLM providers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of providers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: string;
                                provider: string;
                                default_model: string;
                                enabled: boolean;
                                /** Format: date-time */
                                created_at: string;
                                /** Format: date-time */
                                updated_at: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Register or update an LLM provider config */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LlmProviderRequest"];
                };
            };
            responses: {
                /** @description Provider config upserted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmProviderResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/routing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Configure provider routing policy */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoutingRuleRequest"];
                };
            };
            responses: {
                /** @description Routing rule upserted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingRuleResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider health status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                provider: string;
                                /** @enum {string} */
                                status: "healthy" | "degraded" | "down";
                                /** Format: date-time */
                                checked_at: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observability/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated observability metrics over a time window */
        get: {
            parameters: {
                query?: {
                    window_hours?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObservabilityMetricsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observability/release-gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest benchmark release-gate outcome */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest benchmark release gate status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReleaseGatesResponse"];
                    };
                };
                /** @description No benchmark report found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observability/release-gates/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a benchmark report for release-gate tracking */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BenchmarkReportUploadRequest"];
                };
            };
            responses: {
                /** @description Benchmark report stored */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** Format: date-time */
                            created_at: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSessionRequest: {
            data_source_id: string;
            question: string;
        };
        CreateSessionResponse: {
            session_id: string;
            /** @enum {string} */
            status: "created";
        };
        RunSessionRequest: {
            /** @enum {string} */
            llm_provider?: "openai" | "gemini" | "deepseek";
            model?: string;
            max_rows?: number;
            timeout_ms?: number;
        };
        RunSessionResponse: {
            attempt_id: string;
            sql: string;
            columns: string[];
            rows: {
                [key: string]: unknown;
            }[];
            row_count: number;
            duration_ms: number;
            confidence: number;
        };
        FeedbackRequest: {
            rating: number;
            corrected_sql?: string;
            comment?: string;
        };
        OkResponse: {
            ok: boolean;
        };
        CreateDataSourceRequest: {
            name: string;
            /** @enum {string} */
            db_type: "postgres";
            connection_ref: string;
        };
        DataSourceResponse: {
            id: string;
            name: string;
            db_type: string;
            status: string;
        };
        DataSourceListResponse: {
            items: {
                id: string;
                name: string;
                db_type: string;
                connection_ref: string;
                status: string;
                /** Format: date-time */
                created_at: string;
            }[];
        };
        JobAcceptedResponse: {
            job_id: string;
            /** @enum {string} */
            status: "queued";
        };
        SchemaObject: {
            id: string;
            /** @enum {string} */
            object_type: "table" | "view" | "materialized_view";
            schema_name: string;
            object_name: string;
            description?: string;
        };
        SemanticEntityRequest: {
            data_source_id: string;
            /** @enum {string} */
            entity_type: "table" | "column" | "metric" | "dimension" | "rule";
            target_ref: string;
            business_name: string;
            description?: string;
        };
        SemanticEntityResponse: {
            id: string;
            active: boolean;
        };
        MetricDefinitionRequest: {
            semantic_entity_id: string;
            sql_expression: string;
            grain?: string;
        };
        MetricDefinitionResponse: {
            id: string;
        };
        JoinPolicyRequest: {
            data_source_id: string;
            left_ref: string;
            right_ref: string;
            join_type: string;
            on_clause: string;
            approved: boolean;
        };
        JoinPolicyResponse: {
            id: string;
        };
        LlmProviderRequest: {
            /** @enum {string} */
            provider: "openai" | "gemini" | "deepseek";
            api_key_ref: string;
            default_model: string;
            enabled: boolean;
        };
        LlmProviderResponse: {
            provider: string;
            enabled: boolean;
        };
        RoutingRuleRequest: {
            data_source_id: string;
            /** @enum {string} */
            primary_provider: "openai" | "gemini" | "deepseek";
            fallback_providers: ("openai" | "gemini" | "deepseek")[];
            /** @enum {string} */
            strategy: "ordered_fallback" | "cost_optimized" | "latency_optimized";
        };
        RoutingRuleResponse: {
            id: string;
        };
        ObservabilityMetricsResponse: {
            [key: string]: unknown;
        };
        ReleaseGatesResponse: {
            [key: string]: unknown;
        };
        BenchmarkReportUploadRequest: {
            /** Format: date-time */
            run_date: string;
            dataset_file: string;
            data_source_id?: string;
            provider?: string;
            model?: string;
            summary: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: {
        SessionId: string;
        DataSourceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
